from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.config import settings
from src.utils import setup_logger


class MarkdownReportGenerator:
    def __init__(self) -> None:
        self.logger: logging.Logger = setup_logger("MarkdownReport")

    async def generate(self, domains: list[dict[str, Any]], date: str | None = None) -> str:
        date = date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines: list[str] = []
        total = len(domains)

        # Header
        lines.append(f"# Daily Domain Report - {date}")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(f"- **Total domains found:** {total}")
        lines.append(f"- **Report date:** {date}")
        lines.append(f"- **Max bid:** ${settings.max_bid}")
        lines.append(f"- **Preferred range:** ${settings.preferred_min} – ${settings.preferred_max}")
        lines.append("")

        # Key metrics
        scores = [d.get("final_score", 0) or 0 for d in domains if d.get("final_score") is not None]
        avg_score = sum(scores) / len(scores) if scores else 0.0
        grade_counts: dict[str, int] = {}
        for d in domains:
            g = d.get("opportunity_grade", "N/A")
            grade_counts[g] = grade_counts.get(g, 0) + 1

        lines.append("### Key Metrics")
        lines.append("")
        lines.append(f"- **Average score:** {avg_score:.1f}")
        for grade in sorted(grade_counts, key=lambda g: "A+ A B C Avoid N/A".index(g) if g in "A+ A B C Avoid N/A" else 99):
            lines.append(f"- **{grade}:** {grade_counts[grade]}")
        lines.append("")

        # Top 20 table
        lines.append("## Top 20 Domains")
        lines.append("")
        lines.append("| # | Domain | Price | DR | RD | Age | Category | Score | Grade |")
        lines.append("|---|--------|-------|----|----|-----|----------|-------|-------|")
        for i, d in enumerate(domains[:20], 1):
            price = d.get("price", 0) or 0
            dr = d.get("dr", 0) or 0
            rd = d.get("referring_domains", 0) or 0
            age = d.get("domain_age", 0) or 0
            cat = d.get("category", "general") or "general"
            score = d.get("final_score", 0) or 0
            grade = d.get("opportunity_grade", "N/A") or "N/A"
            name = d.get("domain_name", "unknown")
            price_str = f"${price:.2f}" if isinstance(price, (int, float)) else f"${price}"
            age_str = f"{age}y" if age else "-"
            lines.append(f"| {i} | {name} | {price_str} | {dr} | {rd} | {age_str} | {cat} | {score:.0f} | {grade} |")
        lines.append("")

        # Details
        lines.append("## Domain Details")
        lines.append("")
        for i, d in enumerate(domains[:20], 1):
            name = d.get("domain_name", "unknown")
            lines.append(f"### {i}. {name}")
            lines.append("")
            reason = d.get("reason", "")
            if reason:
                lines.append(f"**Reason:** {reason}")
            fields = []
            if d.get("price"):
                fields.append(f"**Price:** ${d['price']}")
            if d.get("registrar"):
                fields.append(f"**Registrar:** {d['registrar']}")
            if d.get("tld"):
                fields.append(f"**TLD:** {d['tld']}")
            if d.get("source"):
                fields.append(f"**Source:** {d['source']}")
            if d.get("trust_score") is not None:
                fields.append(f"**Trust Score:** {d['trust_score']}")
            if d.get("seo_score") is not None:
                fields.append(f"**SEO Score:** {d['seo_score']}")
            if d.get("commercial_score") is not None:
                fields.append(f"**Commercial Score:** {d['commercial_score']}")
            if d.get("cleanliness_score") is not None:
                fields.append(f"**Cleanliness Score:** {d['cleanliness_score']}")
            if d.get("auction_end_date"):
                fields.append(f"**Auction End:** {d['auction_end_date']}")
            if fields:
                lines.append(" | ".join(fields))
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by Domain Flipper Bot on {date}*")

        return "\n".join(lines).strip()

    async def save(self, content: str, filename: str | None = None) -> Path:
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        name = filename or f"report_{date}.md"
        report_dir = Path("data/reports")
        report_dir.mkdir(parents=True, exist_ok=True)
        path = report_dir / name
        path.write_text(content, encoding="utf-8")
        self.logger.info("Markdown report saved to %s", path)
        return path
